### ISSUE TITLE
How to load cdn files??

### ISSUE THREAD

**Issue by brunomacf** [karma-runner/grunt-karma#101]
How do i get the browser to load google recaptcha from cdn link www.google.com/recaptcha/api/js/recaptcha_ajax.js???

**Comment by gvas** [comment]
I believe @brunomacf would like the CDN hosted .js file's URL included in a script tag in the karma-generated test runner HTML file. I also need this. I run my tests on SauceLabs. There is a proxy configured in the SauceLabs browser which routes the file requests either directly to a CDN or to my local machine, depending on the requested file's domain. The idea is to create a test architecture like this:

```
CDN, serves the 3rd party libraries (jQuery, etc)
 │
 │
SauceLabs virtual machine, hosts the browser
 │
 │
Karma on local machine, serves the application- and testfiles
```

So I'd like karma to include the CDN files' URLs in script tags unaltered. I have tried the following config, without success:

```
  {
    ...
    files: [
      { src: ['https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js'], watched: false, served: false, included: true },
      { src: ['app/*.js', 'spec/*.js'] }
    ]
  }
```
The config above results in a html similar to this (http://localhost:9876/debug.html):
```
<html>
  ...
  <script type="text/javascript" src="/base/node_modules/karma-jasmine/lib/jasmine.js"></script>
  <script type="text/javascript" src="/base/node_modules/karma-jasmine/lib/adapter.js"></script>
  <script type="text/javascript" src="/base/app/file1.js"></script>
  <script type="text/javascript" src="/base/spec/test1.js"></script>
</html>
```
There is no script tag for jQuery.

**Comment by eddiemonge** [comment]
This is more of a Karma issue rather than a grunt-karma issue I believe.

**Comment by gvas** [comment]
I've made some progress debugging this issue.
This works:
```
karma: {
    options: {
        ...
        files: [
            'https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js',
            'spec/*.js'
        ]
    },
    all: {}
}
```
This does not ("Arguments to path.resolve must be strings"):
```
karma: {
    options: {
        ...
        files: [
            { src: ['https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js'] },
            { src: ['spec/*.js'] }
        ]
    },
    all: {}
}
```
This neither ("Cannot use 'in' operator to search for 'src' in https://.../jquery.min.js"):
```
karma: {
    options: {
        ...
    },
    all: {
        files: [
            'https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js',
            'spec/*.js'
        ]
    }
}
```
This neither (no error thrown, but the absolute URL is not included in the HTML):
```
karma: {
    options: {
        ...
    },
    all: {
        files: [
            { src: ['https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js'] },
            { src: ['spec/*.js'] }
        ]
    }
}
```

**Comment by gvas** [comment]
... but the last one format can be tweaked. This works:
```
karma: {
    options: {
        ...
    },
    all: {
        files: [
            { src: ['https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js'], nonull: true },
            { src: ['spec/*.js'] }
        ]
    }
}
```

**Comment by Alexandr-Ilyin** [comment]
I've tried some hack and it worked.
I just added script like import.js:

var url = 'http://localhost.dev.kontur:8082/build/bundle_tests.js'
var newScript = document.createElement('script');
newScript.setAttribute('src',url);
document.head.appendChild(newScript);

and included this in files: [ .. ]

**Comment by KaushikRay** [comment]
For me this worked - 
 
// list of files / patterns to load in the browser
    files: [
        'bower_components/angular/angular.js',
        'bower_components/angular-mocks/angular-mocks.js',
        'bower_components/angular-resource/angular-resource.js',
        'app/**/*.*',
        'test/**/*.*',
        'https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js'
    ],

**Comment by Krinkle** [comment]
This is indeed not an issue with grunt-karma, but a support query about Karma itself.

And in current versions, it appears Karma actually does support URLs. See also <https://karma-runner.github.io/2.0/config/configuration-file.html> and <https://karma-runner.github.io/2.0/config/files.html>.
