### ISSUE TITLE
karma hangs at test 16 of 43 consistently until the browser is out of memory

### ISSUE THREAD

**Issue by Giszmo** [karma-runner/grunt-karma#131]
I did whatever change to my code and the automatic karma re-run ran into what seams to be an infinite loop / mem-leak.

I will now try to undo my changes but would also like to see where it happens without random guesses based on what I remember. The browser opening with the debug-button is of no help. If I press debug, it instantly freezes and I get no debug at all. Setting logging to debug I get no info on what "16" might be.

Any hints?

I run Karma version: 0.8.8 with Chrome 37 on Linux.

**Comment by tpaksu** [comment]
Can you add a new test case like `expect(true).toBe(true);` in front of the other test cases? Does it now hang at test 17?

**Comment by Giszmo** [comment]
This issue is five years old. If it works for you, don't bother.

**Comment by tpaksu** [comment]
@Giszmo sorry I didn't check the date :) I was searching for another thing when I saw this issue and wondered if it's related with the tests or karma itself. Thanks for pointing that out.
