### ISSUE TITLE
[ERROR] config - Invalid config file!  [ReferenceError: module is not defined]

### ISSUE THREAD

**Issue by BairDev** [karma-runner/grunt-karma#140]
Hi, we are using grunt-karma (not just karma) and I've tried to use a modularized config file. Like:

<pre>
// Karma configuration
module.exports = function(config) {
  config.set({
    // list of files / patterns to load in the browser
    files: [
      'test/**/*.js' //or whatever
    ]
  });
};
</pre>

But I get the error

<pre>
[ERROR] config - Invalid config file!
 [ReferenceError: module is not defined]
</pre>

I also tried
<pre>
rm -r node_modules/karma
</pre>, but where exactly should I do this, if it is necessary for this plugin at all?

**Comment by MalteFabian** [comment]
oh, versions. package.json:
<pre>
"devDependencies": {
    "grunt": "~0.4.0",
    "grunt-concurrent": "^0.5.0",
    // etc. pp.
    "grunt-html2js": "~0.2.8",
    "grunt-karma": "~0.4.4",
    "istanbul": "^0.3.5",
    "jasmine-spec-reporter": "^1.1.1",
    "karma": "~0.12"
  },
</pre>

Am I totally on the wrong track?

**Comment by Krinkle** [comment]
@BairDev It looks like this error may've come from one of the JavaScript files in your project, and not from code specific to Karma or grunt-karma.

If you are still experiencing an issue, feel free to comment here or report it as a new issue.
