### ISSUE TITLE
0.10.x breaks ng-html2js-preprocessor

### ISSUE THREAD

**Issue by JoshSchreuder** [karma-runner/grunt-karma#146]
Just tried updating to 0.10.0 / 0.10.1 from 0.8.3 which fail to work as I'm using [ng-html2js-preprocessor](https://github.com/karma-runner/karma-ng-html2js-preprocessor).

Rolling back to 0.9.0 works correctly as per 0.8.x behaviour.

I'm not entirely sure what's going on, but I think it is something to do with this commit: @a10aaa7548267ab035f8f4689eb54b2ead9245ef

If I specify preprocessors in my grunt config:
```js
preprocessors: {
     'modules/**/*.js': ['coverage'],
     'modules/**/*.html': ['ng-html2js']
},
```

The template loading in my tests fails (the preprocessor is supposed to load templates into an Angular module) and therefore a bunch of my tests break.

If I specify the above preprocessors in my Karma config, it works correctly, so I suspect there is something wrong with the above commit.

**Comment by Dignifiedquire** [comment]
Could you set the log level to debug and show me the output before and after please?

**Comment by fpoliquin** [comment]
Got the same problem on 0.11.1. Karma preprocessors just don't get executed. Rolling back to 0.9.0.

**Comment by mrfelton** [comment]
Same issue

**Comment by ValentinH** [comment]
Same issue here, I'm investigating it and will try to submit a PR.

**Comment by ValentinH** [comment]
OK found it.
In my karma options, I was setting  ̀basePath: '../'` but this was not used in the commit mentioned above.
