### ISSUE TITLE
Error during the loading "grunt-karma" task

### ISSUE THREAD

**Issue by jimilucio** [karma-runner/grunt-karma#170]
Hi everyone.
I'm dealing with the loading of the "grunt-karma" task inside my Gruntfile.js.
Unfortunately I've got an error, please see below.

> Loading "grunt-karma.js" tasks...ERROR
> TypeError: Cannot promisify an API that has normal methods with 'Async'-suffix
> 
> ```
> See http://goo.gl/iWrZbw
> 
> at checkValid (/Users/my_project/node_modules/karma/node_modules/bluebird/js/main/promisify.js:55:27)
> at promisifiableMethods (/Users/my_project/node_modules/karma/node_modules/bluebird/js/main/promisify.js:78:5)
> at promisifyAll (/Users/my_project/node_modules/karma/node_modules/bluebird/js/main/promisify.js:241:9)
> at Function.Promise.promisifyAll (/Users/my_project/node_modules/karma/node_modules/bluebird/js/main/promisify.js:304:12)
> at Object.<anonymous> (/Users/my_project/node_modules/karma/lib/file-list.js:15:18)
> ```
> 
> ......

It works fine till I launch the command "$karma start my_karma_conf.js".
And it works fine with "grunt-karma" if I remove the promise-require inside the karma/lib/file-list.js on line 15.
// var fs = Promise.promisifyAll(require('fs'));
var fs = require('fs');

What's wrong in my configuration?

I'm using:
karma 0.13.5
grunt-karma 0.12.1

Thank you in advise for your support.

**Comment by Krinkle** [comment]
Thanks for reporting this issue. It seems this was previously reported at https://github.com/karma-runner/grunt-karma/issues/171 and https://github.com/karma-runner/karma/issues/1946. Please look there for more information.
