### ISSUE TITLE
Overriding global "Promise"

### ISSUE THREAD

**Issue by blacha** [karma-runner/grunt-karma#171]
Loading the npm task "grunt-karma" destroys the global "Promise" variable.

running on Node v4.1.0

Gruntfile.js: 

``` javascript
module.exports = function (grunt) {
    console.log('before-karma', Promise.defer);
    grunt.loadNpmTasks('grunt-karma');
    console.log('after-karma', Promise.defer);
}
```

Output: 

```
before-karma function defer() { [native code] }
after-karma undefined
```

**Comment by ogonkov** [comment]
Seems this breaks grunt-postcss task nDmitry/grunt-postcss#87

**Comment by dignifiedquire** [comment]
@ogonkov this is not an issue of karma but a bug in the promise implementation. Ref https://github.com/karma-runner/karma/issues/1946

**Comment by ogonkov** [comment]
@dignifiedquire thank you for sorting out that!

**Comment by Krinkle** [comment]
Closing in favour of https://github.com/karma-runner/karma/issues/1946.
