### ISSUE TITLE
Grunt failing

### ISSUE THREAD

**Issue by paladox** [karma-runner/grunt-karma#184]
21:42:49 npm ERR! peerinvalid Peer grunt-karma@0.12.1 wants grunt@0.4.x

This happends when using 1.0 grunt.

**Comment by paladox** [comment]
@dignifiedquire or @vladikoff hi could you update https://github.com/karma-runner/grunt-karma/blob/master/package.json#L49

Change it to 0.4.0 not 0.4.x since it fails https://integration.wikimedia.org/ci/job/mediawiki-extensions-qunit/35776/console

**Comment by paladox** [comment]
And release 0.12.3 please.

**Comment by TheSavior** [comment]
This is currently causing failures with grunt 1.0 now that it has been released.

**Comment by dignifiedquire** [comment]
The latest version is 0.12.2 which has the correct peerDependency: https://github.com/karma-runner/grunt-karma/blob/master/package.json#L49

**Comment by vladikoff** [comment]
Yay!

**Comment by paladox** [comment]
Thanks, yep it works.
