### ISSUE TITLE
Please remove grunt from peerDependencies from package.json

### ISSUE THREAD

**Issue by paladox** [karma-runner/grunt-karma#185]
Please fix peerDependencies since it is failing grunt 1.0.0

Update 
  "peerDependencies": {
    "grunt": ">=0.4.x"
  },

to

  "peerDependencies": {
    "grunt": ">=0.4.0"
  },

@dignifiedquire or @vladikoff  Please could you do it since I doint want to sign the cla.

**Comment by vladikoff** [comment]
@paladox this is already done, having the ` "grunt": ">=0.4.x",` is good enough.

In your project you are using `grunt-karma@0.12.1 wants grunt@0.4.x` which still had `"grunt": "0.4.x"`

**Comment by vladikoff** [comment]
See 0.12.1 version https://github.com/karma-runner/grunt-karma/blob/v0.12.1/package.json#L47 and compare it with `master`

**Comment by vladikoff** [comment]
@paladox see http://gruntjs.com/blog/2016-02-11-grunt-1.0.0-rc1-released#peer-dependencies

**Comment by paladox** [comment]
Thanks ive asked for this to be released as a 0.12.2 update.

**Comment by paladox** [comment]
Actually see https://github.com/gruntjs/grunt-contrib-watch/commit/1f198f6ec849cc69ac74b24af9362592dd2d610a

**Comment by vladikoff** [comment]
@paladox Yeah you can both remove and keep it. Some developers prefer to keep this setting.

**Comment by paladox** [comment]
@vladikoff do you suggest to keep it, how would we support 1.0 of grunt.

**Comment by paladox** [comment]
Please

**Comment by vladikoff** [comment]
> @vladikoff do you suggest to keep it, how would we support 1.0 of grunt.

 Plugins that will have \>=0.4.0 as a peerDep will just work:

![image](https://cloud.githubusercontent.com/assets/128755/13858795/9ab6a188-ec56-11e5-9099-62d7bb50e96d.png)

(`rc1` is currently failing but that's npm's fault)

**Comment by paladox** [comment]
Oh ok thanks. So its grunt that the problem. Should we file a task with them.

**Comment by paladox** [comment]
Ive reported it here https://github.com/gruntjs/grunt/issues/1488

**Comment by dignifiedquire** [comment]
New version released which should fix this

**Comment by paladox** [comment]
Thanks.
