### ISSUE TITLE
Customize "files" option in Gruntfile

### ISSUE THREAD

**Issue by pauldijou** [karma-runner/grunt-karma#21]
Hi there,

I wanted to override the "files" parameters of my karma.conf.js inside grunt-karma plugin. My use case is having a list of common files (like all AngularJS files) and adding either underscore or lodash to test that the library is compatible with both third part libraries.

My first idea was something like:

``` javascript
karma: {
  options: {
    configFile: 'karma.conf.js',
    browsers: ['PhantomJS']
  },
  buildLodash: {
    files: [
       JASMINE,
       JASMINE_ADAPTER,
      'http://code.angularjs.org/1.1.4/angular.js',
      'http://code.angularjs.org/1.1.4/angular-resource.js',
      'http://code.angularjs.org/1.1.4/angular-mocks.js',
      'http://cdnjs.cloudflare.com/ajax/libs/lodash.js/1.1.1/lodash.js',
      'src/*.js',
      'test/*.js'
      'src/*.js',
      'test/*.js'
    ],
    singleRun: true
  },
  buildUnderscore: {
    files: [
       JASMINE,
       JASMINE_ADAPTER,
      'http://code.angularjs.org/1.1.4/angular.js',
      'http://code.angularjs.org/1.1.4/angular-resource.js',
      'http://code.angularjs.org/1.1.4/angular-mocks.js',
      'http://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.4.4/underscore.js',
      'src/*.js',
      'test/*.js'
    ],
    singleRun: true
  }
}
```

But that didn't work because JASMINE is not defined... fair enough. Is there a way to define both JASMINE and JASMINE_ADAPTER? I saw there was defined inside `grunt-karma/node_modules/karma/lib/config.js` but I have no idea how to import them...

As an alternative, what would think about a way to extend the arrays from the config file rather than only overriding them? Something like `filesExtend`, `exludeExtend`, `reportersExtend` and `browersExtend` options which would apply a `concat` between the array from the karma.conf.js file and the Gruntfile. It could be extend a second time inside tasks. Example:

**karma.conf.js**

``` javascript
files = [
  JASMINE,
  JASMINE_ADAPTER
]
```

**Gruntfile.js**

``` javascript
karma: {
  options: {
    configFile: 'karma.conf.js',
    browsers: ['PhantomJS'],
    filesExtend: [
      'http://code.angularjs.org/1.1.4/angular.js',
      'http://code.angularjs.org/1.1.4/angular-resource.js',
      'http://code.angularjs.org/1.1.4/angular-mocks.js',
      'src/*.js',
      'test/*.js'
    ]
  },
  buildLodash: {
    filesExtend: [
      'http://cdnjs.cloudflare.com/ajax/libs/lodash.js/1.1.1/lodash.js'
    ],
    singleRun: true
  },
  buildUnderscore: {
    filesExtend: [
      'http://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.4.4/underscore.js'
    ],
    singleRun: true
  }
}
```

This would produce the expected result : both builds would have all AngularJS and JASMINE files, and either lodash or underscore depending on the task.

What do you think?

**Comment by bennyn** [comment]
For me this setup was working (since it did not work like explained in the README):

**karma.coffee**

```coffeescript
module.exports =
  options:
    configFile: 'karma.conf.js'
    files: [
      # vendor files
      'ext/js/jquery.js',
      'ext/js/amplify.js',
      # helper files
      '../test/lib/mock-ajax-3.2.0.js',
      '../test/lib/sinon-1.17.3.js',
      '../test/api/payloads.js',
      # app files
      {pattern: 'proto/messages.proto', included: false, served: true, nocache: true},
      'script/config.js',
      'script/main/*.js',
    ]
  test:
    colors: false
```

**Grunfile.coffee**

```coffeescript
grunt.registerTask 'test_run', (test_name) ->
  test_file = "../test/js/#{test_name}Spec.js" if test_name
  original_files = grunt.config.get 'karma.options.files'
  grunt.config 'karma.options.files', [].concat original_files, [test_file]
  grunt.task.run [
    # Transpile app files (business logic)
    'newer:coffee:app'
    # Transpile test files
    'newer:coffee:test'
    # Run tests with Karma
    'karma:test'
  ]
```

This gives me the ability to run individual Jasmine tests (like "`../test/js/main/AppStartSpec.js`") with a commands like this: `grunt test_run:main/AppStart`

**Comment by Krinkle** [comment]
This seems to be a request for an additional ability (customisation of `files`), but also in part a support thread about how to achieve the underlying use case.

I'm declining the feature request part of this. I don't think we can provide a customizable `files` option in a way that is easy to use and maintain.

The use case itself (re-using parts of the file list) can be achieved by storing it in an array and using part of that twice. As demonstrated by others already, it can be used twice by reference, using [Array#concat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat). In newer versions of Node.js, one may also also consider the [spread syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax).
