### ISSUE TITLE
Release grunt-karma 3.0

### ISSUE THREAD

**Issue by johnjbarton** [karma-runner/grunt-karma#261]
@Krinkle assign this to me when you are ready (the release scripts have some issues I am trying to iron).

IMO the package.json should dep karma ^3.0.0 since that is where the integration tests run.

**Comment by Krinkle** [comment]
@johnjbarton Thanks, will do. By the way, which integration tests are you referring to?

**Comment by johnjbarton** [comment]
https://github.com/karma-runner/karma/search?q=integration-tests.sh&unscoped_q=integration-tests.sh

**Comment by Krinkle** [comment]
@johnjbarton Tthe [integration tests](https://github.com/karma-runner/integration-tests) don't currently cover grunt-karma (I think). Is your intention to make just make sure we are testing and passing with the latest version of Karma (devDeps), or were you referring the peerDeps support requirement?

One the projects I work on uses grunt-karma 2.0 with karma 2.x, and while it runs fine, it surprises me that it installs without warnings. I'd expect npm to warn about the specified version in package.json (karma@2.0.2) not satisfying grunt-karma's `^0.13.0 || ^1.0.0` peer dependency. But.. that maybe be a problem for another time.

Can we / should we continue to support the older versions, or add 3.x to the pipe?

**Comment by johnjbarton** [comment]
I think new the top priority is for new versions of grunt-karma to support the newest versions of karma-runner.   For most cases that is enough. There may be circumstances where mixing versions is needed, but I don't think the extra work is justified compared to other priorities.

**Comment by johnjbarton** [comment]
Sorry I can't get to this until ~24th. I tried today but ran into some issues with login and I will be out on vacation.

**Comment by johnjbarton** [comment]
3.0 is up
