### ISSUE TITLE
Release grunt-karma 3.0.1

### ISSUE THREAD

**Issue by Krinkle** [karma-runner/grunt-karma#269]
Commits:
* https://github.com/karma-runner/grunt-karma/commit/579f82f1e4d65f3e18eb2083bd9a926f7b9d7a72 – feat(karma): require karma 3 in peerDependencies
* https://github.com/karma-runner/grunt-karma/commit/2f0d53ad2c594a426dfd7c4b09422d2ddb3eb314 – docs(readme): Reflect the currently required Karma version

Fixes:
* https://github.com/karma-runner/grunt-karma/issues/267#issuecomment-420502329 – False "npm Warning" about peer dependencies.

**Comment by johnjbarton** [comment]
done https://github.com/karma-runner/grunt-karma/releases/tag/v3.0.1
