### ISSUE TITLE
Grunt templates

### ISSUE THREAD

**Issue by eddiemonge** [karma-runner/grunt-karma#46]
What does this line do: https://github.com/karma-runner/grunt-karma/blob/master/tasks/grunt-karma.js#L27

As far as I can tell, it only returns the data.configFile path as a string, which it already was. 

I was hoping it would process <%= => in the config file, but sadly it doesnt.

**Comment by Dignifiedquire** [comment]
@eddiemonge I believe this doable in the latest release, could you check please?

**Comment by eddiemonge** [comment]
I really want to close this as I don't remember what I needed this to do/found other solutions since then.
